export const QUEUE_NOTIFICATION = 'QUEUE_NOTIFICATION';
export const QUEUE_INVOICE = 'QUEUE_INVOICE';
export const QUEUE_PAYMENT = 'QUEUE_PAYMENT';
export const QUEUE_MAINTENANCE = 'QUEUE_MAINTENANCE';

export const JOB_DISPATCH_NOTIFICATION = 'DISPATCH_NOTIFICATION';
export const JOB_DISPATCH_MULTI_NOTIFICATION = 'DISPATCH_MULTI_NOTIFICATION';
export const JOB_GENERATE_INVOICE_PDF = 'GENERATE_INVOICE_PDF';
export const JOB_RECONCILE_PAYMENT_ASYNC = 'RECONCILE_PAYMENT_ASYNC';
export const JOB_CLEANUP_EXPIRED_TOKENS = 'CLEANUP_EXPIRED_TOKENS';
export const JOB_CLEANUP_OLD_NOTIFICATIONS = 'CLEANUP_OLD_NOTIFICATIONS';
