import { NavItem, NavigationRegistry } from './registry';

export const ADMIN_NAVIGATION_CONFIG: NavItem[] = [
  {
    id: 'nav-dashboard',
    title: 'Overview',
    href: '/',
    icon: 'grid',
    roles: ['ADMIN'],
    order: 1,
    requiresAuth: true,
    breadcrumb: 'Dashboard Overview',
    description: 'System metrics and operational status',
  },
  {
    id: 'nav-users',
    title: 'Users',
    href: '/users',
    icon: 'user',
    roles: ['ADMIN'],
    order: 2,
    requiresAuth: true,
    disabled: true,
    badge: 'Phase 8',
    description: 'User management reserved for Phase 8',
  },
  {
    id: 'nav-service-requests',
    title: 'Service Requests',
    href: '/service-requests',
    icon: 'briefcase',
    roles: ['ADMIN'],
    order: 3,
    requiresAuth: true,
    disabled: true,
    badge: 'Phase 4',
    description: 'Service request management reserved for Phase 4',
  },
  {
    id: 'nav-surveys',
    title: 'Surveys',
    href: '/surveys',
    icon: 'file-text',
    roles: ['ADMIN'],
    order: 4,
    requiresAuth: true,
    disabled: true,
    badge: 'Phase 5',
    description: 'Survey management reserved for Phase 5',
  },
  {
    id: 'nav-estimates',
    title: 'Estimates',
    href: '/estimates',
    icon: 'file-text',
    roles: ['ADMIN'],
    order: 5,
    requiresAuth: true,
    disabled: true,
    badge: 'Phase 6',
    description: 'Estimate management reserved for Phase 6',
  },
  {
    id: 'nav-work-orders',
    title: 'Work Orders',
    href: '/work-orders',
    icon: 'briefcase',
    roles: ['ADMIN'],
    order: 6,
    requiresAuth: true,
    disabled: true,
    badge: 'Phase 7',
    description: 'Work order management reserved for Phase 7',
  },
  {
    id: 'nav-payments',
    title: 'Payments',
    href: '/payments',
    icon: 'briefcase',
    roles: ['ADMIN'],
    order: 7,
    requiresAuth: true,
    disabled: true,
    badge: 'Phase 9',
    description: 'Payment processing reserved for Phase 9',
  },
  {
    id: 'nav-invoices',
    title: 'Invoices',
    href: '/invoices',
    icon: 'file-text',
    roles: ['ADMIN'],
    order: 8,
    requiresAuth: true,
    disabled: true,
    badge: 'Phase 10',
    description: 'Invoicing reserved for Phase 10',
  },
  {
    id: 'nav-reports',
    title: 'Reports',
    href: '/reports',
    icon: 'file-text',
    roles: ['ADMIN'],
    order: 9,
    requiresAuth: true,
    disabled: true,
    badge: 'Phase 11',
    description: 'Analytics and reporting reserved for Phase 11',
  },
  {
    id: 'nav-settings',
    title: 'Settings',
    href: '/settings',
    icon: 'settings',
    roles: ['ADMIN'],
    order: 10,
    requiresAuth: true,
    breadcrumb: 'System Settings',
    description: 'Platform parameters and options',
  },
];

// Initialize Navigation Registry for Admin
NavigationRegistry.registerItems(ADMIN_NAVIGATION_CONFIG);
