import { NavItem, NavigationRegistry } from './registry';

export const ADMIN_NAVIGATION_CONFIG: NavItem[] = [
  {
    id: 'nav-dashboard',
    title: 'Overview',
    href: '/',
    icon: 'grid',
    roles: ['ADMIN'],
    order: 1,
    requiresAuth: true,
    breadcrumb: 'Dashboard Overview',
    description: 'System metrics and operational status',
  },
  {
    id: 'nav-users',
    title: 'Users',
    href: '/users',
    icon: 'user',
    roles: ['ADMIN'],
    order: 2,
    requiresAuth: true,
    disabled: false,
    badge: 'Active',
    breadcrumb: 'User Management',
    description: 'User accounts and role administration',
  },
  {
    id: 'nav-service-requests',
    title: 'Service Requests',
    href: '/service-requests',
    icon: 'briefcase',
    roles: ['ADMIN'],
    order: 3,
    requiresAuth: true,
    disabled: false,
    badge: 'Active',
    breadcrumb: 'Service Request Management',
    description: 'Service request lifecycle and assignment',
  },
  {
    id: 'nav-surveys',
    title: 'Surveys',
    href: '/surveys',
    icon: 'file-text',
    roles: ['ADMIN'],
    order: 4,
    requiresAuth: true,
    disabled: false,
    badge: 'Active',
    breadcrumb: 'Technical Survey & Inspection',
    description: 'Survey inspection form review and approval',
  },
  {
    id: 'nav-estimates',
    title: 'Estimates',
    href: '/estimates',
    icon: 'file-text',
    roles: ['ADMIN'],
    order: 5,
    requiresAuth: true,
    disabled: false,
    badge: 'Active',
    breadcrumb: 'Estimate Quotation Management',
    description: 'Pricing calculation, line items, and approval',
  },
  {
    id: 'nav-work-orders',
    title: 'Work Orders',
    href: '/work-orders',
    icon: 'briefcase',
    roles: ['ADMIN'],
    order: 6,
    requiresAuth: true,
    disabled: false,
    badge: 'Active',
    breadcrumb: 'Work Order Management & Execution',
    description: 'Work order execution lifecycle, scheduling, and QA verification',
  },
  {
    id: 'nav-invoices',
    title: 'Invoices',
    href: '/invoices',
    icon: 'file-text',
    roles: ['ADMIN'],
    order: 7,
    requiresAuth: true,
    disabled: false,
    badge: 'Active',
    breadcrumb: 'Invoice Management & Billing',
    description: 'Financial billing statements, line items, and due dates',
  },
  {
    id: 'nav-payments',
    title: 'Payments',
    href: '/payments',
    icon: 'briefcase',
    roles: ['ADMIN'],
    order: 8,
    requiresAuth: true,
    disabled: false,
    badge: 'Active',
    breadcrumb: 'Payment & Transaction Management',
    description: 'Payment sessions, gateway checkout, and manual reconciliation',
  },
  {
    id: 'nav-storage',
    title: 'Storage',
    href: '/storage',
    icon: 'file-text',
    roles: ['ADMIN'],
    order: 9,
    requiresAuth: true,
    disabled: false,
    badge: 'Active',
    breadcrumb: 'File & Storage Management',
    description: 'Asset storage, signed download URLs, and attachment management',
  },
  {
    id: 'nav-reports',
    title: 'Reports',
    href: '/reports',
    icon: 'file-text',
    roles: ['ADMIN'],
    order: 10,
    requiresAuth: true,
    disabled: true,
    badge: 'Phase 13',
    description: 'Analytics and reporting reserved for Phase 13',
  },
  {
    id: 'nav-settings',
    title: 'Settings',
    href: '/settings',
    icon: 'settings',
    roles: ['ADMIN'],
    order: 11,
    requiresAuth: true,
    breadcrumb: 'System Settings',
    description: 'Platform parameters and options',
  },
];

// Initialize Navigation Registry for Admin
NavigationRegistry.registerItems(ADMIN_NAVIGATION_CONFIG);
