import { NavItem, NavigationRegistry } from './registry';

export const CUSTOMER_NAVIGATION_CONFIG: NavItem[] = [
  {
    id: 'customer-home',
    title: 'Home',
    href: '/',
    icon: 'grid',
    roles: ['CUSTOMER'],
    order: 1,
    requiresAuth: true,
  },
  {
    id: 'customer-requests',
    title: 'Requests',
    href: '/service-requests',
    icon: 'briefcase',
    roles: ['CUSTOMER'],
    order: 2,
    requiresAuth: true,
  },
  {
    id: 'customer-surveys',
    title: 'Surveys',
    href: '/surveys',
    icon: 'file-text',
    roles: ['CUSTOMER'],
    order: 3,
    requiresAuth: true,
  },
  {
    id: 'customer-estimates',
    title: 'Estimates',
    href: '/estimates',
    icon: 'file-text',
    roles: ['CUSTOMER'],
    order: 4,
    requiresAuth: true,
  },
  {
    id: 'customer-work-orders',
    title: 'Work Orders',
    href: '/work-orders',
    icon: 'briefcase',
    roles: ['CUSTOMER'],
    order: 5,
    requiresAuth: true,
    disabled: false,
    badge: 'Active',
  },
  {
    id: 'customer-profile',
    title: 'Profile',
    href: '/profile',
    icon: 'user',
    roles: ['CUSTOMER'],
    order: 6,
    requiresAuth: true,
  },
  {
    id: 'customer-settings',
    title: 'Settings',
    href: '/settings',
    icon: 'settings',
    roles: ['CUSTOMER'],
    order: 7,
    requiresAuth: true,
  },
];

NavigationRegistry.registerItems(CUSTOMER_NAVIGATION_CONFIG);
