import { NavItem, NavigationRegistry } from './registry';

export const CUSTOMER_NAVIGATION_CONFIG: NavItem[] = [
  {
    id: 'customer-home',
    title: 'Home',
    href: '/',
    icon: 'grid',
    roles: ['CUSTOMER'],
    order: 1,
    requiresAuth: true,
  },
  {
    id: 'customer-requests',
    title: 'Requests',
    href: '/service-requests',
    icon: 'briefcase',
    roles: ['CUSTOMER'],
    order: 2,
    requiresAuth: true,
  },
  {
    id: 'customer-surveys',
    title: 'Surveys',
    href: '/surveys',
    icon: 'file-text',
    roles: ['CUSTOMER'],
    order: 3,
    requiresAuth: true,
  },
  {
    id: 'customer-estimates',
    title: 'Estimates',
    href: '/estimates',
    icon: 'file-text',
    roles: ['CUSTOMER'],
    order: 4,
    requiresAuth: true,
  },
  {
    id: 'customer-work-orders',
    title: 'Work Orders',
    href: '/work-orders',
    icon: 'briefcase',
    roles: ['CUSTOMER'],
    order: 5,
    requiresAuth: true,
  },
  {
    id: 'customer-invoices',
    title: 'Invoices',
    href: '/invoices',
    icon: 'file-text',
    roles: ['CUSTOMER'],
    order: 6,
    requiresAuth: true,
  },
  {
    id: 'customer-payments',
    title: 'Payments',
    href: '/payments',
    icon: 'briefcase',
    roles: ['CUSTOMER'],
    order: 7,
    requiresAuth: true,
  },
  {
    id: 'customer-storage',
    title: 'Storage',
    href: '/storage',
    icon: 'file-text',
    roles: ['CUSTOMER'],
    order: 8,
    requiresAuth: true,
  },
  {
    id: 'customer-search',
    title: 'Search',
    href: '/search',
    icon: 'search',
    roles: ['CUSTOMER'],
    order: 9,
    requiresAuth: true,
  },
  {
    id: 'customer-activity',
    title: 'Activity',
    href: '/activity',
    icon: 'file-text',
    roles: ['CUSTOMER'],
    order: 10,
    requiresAuth: true,
  },
  {
    id: 'customer-reports',
    title: 'Reports',
    href: '/reports',
    icon: 'file-text',
    roles: ['CUSTOMER'],
    order: 11,
    requiresAuth: true,
    disabled: false,
    badge: 'Active',
  },
  {
    id: 'customer-profile',
    title: 'Profile',
    href: '/profile',
    icon: 'user',
    roles: ['CUSTOMER'],
    order: 12,
    requiresAuth: true,
  },
  {
    id: 'customer-settings',
    title: 'Settings',
    href: '/settings',
    icon: 'settings',
    roles: ['CUSTOMER'],
    order: 13,
    requiresAuth: true,
  },
];

NavigationRegistry.registerItems(CUSTOMER_NAVIGATION_CONFIG);
